// Datos de productos compartidos para todas las páginas.
// NORMALIZADO: precios como números, subcategorías definidas por campo 'subcat'
const products = [
  { id: 1,  qty: 0, name: "Vestido lino beige", cat: "Mujer", subcat: "Vestidos", price: 189, image: "img/Vestido-lino-beige-m.png", bg: "#F1EFE8", badge: "new" },
  { id: 2,  qty: 0, name: "Blazer oversized", cat: "Mujer", subcat: "Abrigos", price: 249, oldPrice: 320, image: "img/Blazer-oversized-m.png", bg: "#E6F1FB", badge: "sale" },
  { id: 3,  qty: 0, name: "Jogger premium", cat: "Hombre", subcat: "Pantalones", price: 139, image: "img/Jogger-premium-h.png", bg: "#E1F5EE", badge: "new" },
  { id: 4,  qty: 0, name: "Camiseta essentials", cat: "Hombre", subcat: "Tops", price: 79, oldPrice: 110, image: "img/Camiseta-essentials.jpg", bg: "#FAECE7", badge: "sale" },
  { id: 5,  qty: 0, name: "Falda midi plisada", cat: "Mujer", subcat: "Pantalones", price: 159, image: "img/Falda-midi-plisada.png", bg: "#FBEAF0", badge: "new" },
  { id: 6,  qty: 0, name: "Chaqueta denim", cat: "Hombre", subcat: "Abrigos", price: 199, oldPrice: 260, image: "img/Chaqueta-denim.png", bg: "#F1EFE8", badge: "sale" },
  { id: 7,  qty: 0, name: "Pantalon acampanado con correa", cat: "Mujer", subcat: "Pantalones", price: 159, image: "img/Pantalon-acampanado-con-correa-m.png", bg: "pink", badge: "new" },
  { id: 8,  qty: 0, name: "Camisa stretch", cat: "Hombre", subcat: "Tops", price: 89.95, image: "img/Camisa-stretch.png", bg: "#FAECE7", badge: "new" },
  { id: 9,  qty: 0, name: "Vestido con hombreras", cat: "Mujer", subcat: "Vestidos", price: 189, image: "img/Vestido-con-hombreras.png", bg: "pink", badge: "new" },
  { id: 10, qty: 0, name: "Chompa con medio cierre", cat: "Hombre", subcat: "Tops", price: 89.95, image: "img/Chompa-con-medio-cierre.png", bg: "#FAECE7", badge: "new" },
  { id: 11, qty: 0, name: "Chompa camisera", cat: "Mujer", subcat: "Tops", price: 89.95, image: "img/Chompa-camisera.png", bg: "pink", badge: "new" },
  { id: 12, qty: 0, name: "Casaca de beisbol", cat: "Hombre", subcat: "Abrigos", price: 159, image: "img/Casaca-de-beisbol.png", bg: "#FAECE7", badge: "new" },
  { id: 13, qty: 0, name: "Top frunces manga larga", cat: "Mujer", subcat: "Tops", price: 139, image: "img/Top-frunces-manga-larga.png", bg: "#FBEAF0", badge: "new" },
  { id: 14, qty: 0, name: "Pantalon jogger", cat: "Hombre", subcat: "Pantalones", price: 159, image: "img/Pantalon-jogger.png", bg: "#FAECE7", badge: "new" },
  { id: 15, qty: 0, name: "Body lazadas espalda descubierta", cat: "Mujer", subcat: "Tops", price: 109, image: "img/Body-lazadas-espalda-descubierta.png", bg: "#FBEAF0", badge: "new" },
  { id: 16, qty: 0, name: "Jean Clasicos", cat: "Hombre", subcat: "Pantalones", price: 86, oldPrice: 150, image: "img/Jean-h.png", bg: "#FAECE7", badge: "sale" },
  { id: 17, qty: 0, name: "Blusa con Escote", cat: "Mujer", subcat: "Tops", price: 69, image: "img/Blusa-con-escote.png", bg: "#FBEAF0", badge: "new" },
  { id: 18, qty: 0, name: "Polo con cuello", cat: "Hombre", subcat: "Tops", price: 49, image: "img/polo.png", bg: "#FAECE7", badge: "new" },
  { id: 19, qty: 0, name: "Buzo Colloky", cat: "Mujer", subcat: "Tops", price: 39.90, image: "img/buzo-m.png", bg: "#F1EFE8", badge: "new" },
  { id: 20, qty: 0, name: "Chaqueta de Cuero", cat: "Hombre", subcat: "Abrigos", price: 79, image: "img/Chaqueta-cuero-h.png", bg: "#E1F5EE", badge: "new" },
  { id: 21, qty: 0, name: "Jean Cortto", cat: "Mujer", subcat: "Pantalones", price: 56, image: "img/Jean-corto-m.png", bg: "#E6F1FB", badge: "new" },
  { id: 22, qty: 0, name: "Camisa Manga Larga", cat: "Hombre", subcat: "Tops", price: 37, image: "img/Camisa-h.png", bg: "#FAECE7", badge: "new" },
  { id: 23, qty: 0, name: "Vestido Midi", cat: "Mujer", subcat: "Vestidos", price: 83, image: "img/Vestido-midi-m.png", bg: "#FBEAF0", badge: "new" },
  { id: 24, qty: 0, name: "Chaqueta Cortaviento", cat: "Hombre", subcat: "Abrigos", price: 62, image: "img/Casaca-h.png", bg: "#E1F5EE", badge: "new" },
  { id: 25, qty: 0, name: "Chaqueta de Cuero", cat: "Mujer", subcat: "Abrigos", price: 70, image: "img/Chaqueta-cuero-m.png", bg: "#E6F1FB", badge: "new" },
  { id: 26, qty: 0, name: "Polo Manga Larga", cat: "Hombre", subcat: "Tops", price: 83, image: "img/Polo-manga-larga-h.png", bg: "#FAECE7", badge: "new" },
  { id: 27, qty: 0, name: "Casaca de Invierno", cat: "Mujer", subcat: "Abrigos", price: 73, image: "img/Casaca-m.png", bg: "#FBEAF0", badge: "new" },
  { id: 28, qty: 0, name: "Abrigo de Lana", cat: "Hombre", subcat: "Abrigos", price: 98, image: "img/Abrigo-lana-h.png", bg: "#E1F5EE", badge: "new" },
  { id: 29, qty: 0, name: "Pantalon Ancho", cat: "Mujer", subcat: "Pantalones", price: 58, image: "img/Palazzo-ancho-m.png", bg: "#E6F1FB", badge: "new" },
  { id: 30, qty: 0, name: "Abrigo Largo de Vestir", cat: "Hombre", subcat: "Abrigos", price: 73, oldPrice: 120, image: "img/Abrigo-h.png", bg: "#FAECE7", badge: "sale" },
  { id: 31, qty: 0, name: "Pantalon de bota Ancha", cat: "Mujer", subcat: "Pantalones", price: 94, image: "img/Pantalon-m.png", bg: "#FBEAF0", badge: "new" },
  { id: 32, qty: 0, name: "Abrigo con Capucha", cat: "Hombre", subcat: "Abrigos", price: 85, image: "img/Abrigo-capucha-h.png", bg: "#E1F5EE", badge: "new" },
  { id: 33, qty: 0, name: "Chaqueta de Jean", cat: "Mujer", subcat: "Abrigos", price: 92, image: "img/Chaqueta-jean-m.png", bg: "#E6F1FB", badge: "new" },
  { id: 34, qty: 0, name: "Abrigo para el Invierno", cat: "Hombre", subcat: "Abrigos", price: 45, image: "img/Abrigo-frio-h.png", bg: "#FAECE7", badge: "new" },
  { id: 35, qty: 0, name: "Top", cat: "Mujer", subcat: "Tops", price: 76, image: "img/Top-m.png", bg: "#FBEAF0", badge: "new" },
  { id: 36, qty: 0, name: "Abrigo de Lana", cat: "Hombre", subcat: "Abrigos", price: 82, image: "img/Abrigo-lana2-h.png", bg: "#E1F5EE", badge: "new" },
  { id: 37, qty: 0, name: "Top Manga Larga", cat: "Mujer", subcat: "Tops", price: 91, image: "img/Top2-m.png", bg: "#E6F1FB", badge: "new" },
  { id: 38, qty: 0, name: "Abrigo Largo de Lana", cat: "Hombre", subcat: "Abrigos", price: 73, image: "img/Abrigo2-h.png", bg: "#FAECE7", badge: "new" },
  { id: 39, qty: 0, name: "Camisa Manga Larga", cat: "Mujer", subcat: "Tops", price: 91, image: "img/Camisa-m.png", bg: "#FBEAF0", badge: "new" },
  { id: 40, qty: 0, name: "Abrigo Largo con Capucha", cat: "Hombre", subcat: "Abrigos", price: 84, oldPrice: 160, image: "img/Abrigo-capucha2-h.png", bg: "#E1F5EE", badge: "sale" }
];

// EXPONER GLOBALMENTE
window.products = products;
